### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by e-bug** [clp-research/image-description-sequences#3]
Hi guys, thanks for making this data set easily accessible.

Please note that one description in `data/sequences.csv` is missing: `d5` for `image_id == 101320`.

**Comment by nilinykh** [comment]
Hey,

yes, this description sequence is spoiled. `d5` for this image is `n\a` that the worker has submitted. It has been overlooked, thank you for pointing this out.

Updated version of the dataset will be in the repo once the corresponding pull request is approved.

p.s. also sent it to you via e-mail
